### ISSUE TITLE
Mirador shows no image after using of the mirador-image-tools

### ISSUE THREAD

**Issue by ChrisBethgster** [ProjectMirador/mirador-image-tools#38] opened 2021-02-12 06:02 UTC
For reproducing - use the mirador-image-tools.netlify.app instance.

- open for example the following manifest: https://iiif.europeana.eu/presentation/9200396/BibliographicResource_3000118436165/manifest
- use the image tools
    - click "Show image tools"
    - use "Invert colors" for example --> the image is correct inverted
- enable "Thumbnails" on bottom
-  click on a thumbnail (WITHOUT scrolling)
- use the image tools -> it works also
- use the scrollbar for selecting a new thumbnail
- try to use image tools 
    - use "Invert colors" for example  -> no image is visible in mirador
![2021-02-12 06_57_59-mirador-image-tools 0 10 0 Demo](https://user-images.githubusercontent.com/54576195/107735324-b9869f80-6cff-11eb-8453-ec45554471c5.png)
- select an other thumbnail  -> also no image is shown

**Comment by sete-arch** [comment] 2021-09-17 13:42
Hi,

I encountered the same problem.

- use the image tools
    click "Show image tools"
    use "Invert colors" for example --> the image is correct inverted
- click on the button "next"
- use the image tools -> it works also
- click on the button "next" twice (or more)
- try to use image tools -> doesn't work, no visible image

Is there any progress on this issue ?

Thank you

**Comment by Marcel-Tronco** [comment] 2024-10-07 14:16
Hi, the problem is still there.
For any developers interested in this, in my console indicated that this is because of a rotation value turning NaN.

```javascript
Unsupported rotation: NaN [index.html:13441:25]<...> index.html)
    overrideMethod <...>/index.html:13441
    onUpdateViewport <...>/main.js:85
    getHandler <...>/2.main.js:6
    raiseEvent <...>/2.main.js:6
    (Async: FrameRequestCallback)
/*...*/
```
Best

**Comment by Marcel-Tronco** [comment] 2024-10-08 08:58
I fidled around with this a while longer and tried to reproduce the bug in mirador dev setup to look at it a little closer, i.e. having setup of the mirador repo developing it with webpack serve (using the start scripts) and using the plugin as a preconfigured one there. In this setup the problem **does not** arise.

I don't know what this means exactly, but made me think of some build/dependency issues as the source of the bug.

Best

**Comment by Marcel-Tronco** [comment] 2024-10-23 11:50
I had some time again to look into it. Concerning the [last](https://github.com/ProjectMirador/mirador-image-tools/issues/38#issuecomment-2399266455) comment testing a little bit longer showed, problems in the other setup are the same.

Yet with the help of react dev tools in the browser I saw that the viewerConfig seems to be (part) of the problem.

Leafing through a manifest in the viewer there are several points, when after changing the page the viewerConfig Prop of the OSD-viewer element and the image tools element becomes `null`. Now if we continue leafing without changing settings in the image tools for the next page this might reset to the old config we saw a page before eventually and never is known, as it doesn't have effects.

If in such a situation we change a setting in the image tools the viewerConfig gets set with only the image tool config part and breaks the viewer, now leafing forward or backward, doesn't change the config leaving it broken.

**Comment by Marcel-Tronco** [comment] 2024-10-24 09:28
Tracked the problem a little further. It seems to be related to the way the viewer handles state in the reducers. Normally the default values for the viewerConfig come from a updateViewport-Function. During a page change (e.g. clicking previous/next page buttons) a setCanvas action first resets the config, without the "defaults", only in another state change action triggered by the updateViewport-Func. the defaults are set. In some circumstances the order is changed and there is not no viewport update after the setCanvas action and the viewerConfig stays null, leading to the problem described above.

**Comment by DiegoPino** [comment] 2024-11-19 19:00
We are having the same problem. Not sure if the open pull for 4.0 fixes these issues, but probably we want to tackle a fix as a community? If not sadly this plugin is not very useful and leads to user frustration

**Comment by lutzhelm** [comment] 2024-11-21 14:43
I just tested the [mirador4-compat-clean](https://github.com/ProjectMirador/mirador-image-tools/pull/49) branch; the problem still exists there, but after that I tried installing Mirador locally with the latest commit https://github.com/ProjectMirador/mirador/commit/c2943e65374fe622a215da228a2e016c9c0c869a from the master branch, et voilà, the changes that are necessary to get it to run made the problem disappear. (Which isn't that surprising because the `react-sizeme`-dependency was replaced with the `ResizeObserver` browser API via ProjectMirador/mirador#3959)

If anyone wants to reproduce this:
* checkout mirador, run
  * `npm install`
  * `npm run prepublishOnly`
  * `npm pack`
* checkout mirador-image-tools, run `npm install ../mirador/mirador-4.0.0-alpha.2.tgz` (adjusted for the actual path)
* replace [this line](https://github.com/ProjectMirador/mirador-image-tools/blob/6e4ef5e92b08eb4dd3f6642b956444ad0fe64f2e/src/plugins/MiradorImageTools.js#L4) with `import { withSize } from 'mirador/dist/es/src/extend/withSize';`
* run `npm run start` and try to reproduce the issue

**Comment by DiegoPino** [comment] 2024-11-22 17:24
@lutzhelm great. Can confirm, the resizeObserver actually does the trick.At least for me, changing the line in this plugin was not needed, just adding react-sizeme as a dependency. Thanks

**Comment by fstoe** [comment] 2024-11-25 12:12
I tried with just adding react-sizeme as a dependency and the plugin doesn't crash but don't work as intended. 
 (for example the tools should kind of be rotated by 90  degree)

**Comment by fstoe** [comment] 2024-11-25 12:53
I tried both approaches and found that they fix the unshown image bug. However they introduce a new one as the original sizing is no longer working (size.width always remains undefined)

In a [pr](https://github.com/ProjectMirador/mirador-image-tools/pull/52) on the mirador4-compat-clean branch, I refactored the component to handle the `withSize` HOC from Mirador.

**Comment by DiegoPino** [comment] 2024-11-25 13:42
@fstoe thanks. this is great!

**Comment by lutzhelm** [comment] 2024-12-06 09:36
There is now a public preview that appears to be working fine: https://deploy-preview-49--mirador-image-tools.netlify.app/

**Comment by lutzhelm** [comment] 2024-12-17 07:45
This is fixed on the master branch now (which is only compatible with the latest Mirador 4 alpha).

**Closed by lutzhelm** 2024-12-17 07:45 UTC
Labels: bug
